export const sriLankaData = {
  name: "Sri Lanka",
  native_name: "ශ්රී ලංකාව / இலங்கை",
  iso2: "LK",
  iso3: "LKA",
  phone_code: "94",
  capital: "Sri Jayawardenepura Kotte",
  currency: "LKR",
  languages: ["Sinhala", "Tamil"],
  provinces: [
    {
      id: 1,
      name: "Western Province",
      name_si: "බස්නාහිර පළාත",
      name_ta: "மேல் மாகாணம்",
      districts: [
        {
          id: 1,
          name: "Colombo",
          name_si: "කොළඹ",
          name_ta: "கொழும்பு",
          cities: [
            { id: 1, name: "Colombo", postcode: "00000" },
            { id: 2, name: "Dehiwala-Mount Lavinia", postcode: "10350" },
            { id: 3, name: "Moratuwa", postcode: "10400" },
            { id: 4, name: "Sri Jayawardenepura Kotte", postcode: "10100" },
            { id: 5, name: "Kolonnawa", postcode: "10600" },
            { id: 6, name: "Kaduwela", postcode: "10640" },
            { id: 7, name: "Homagama", postcode: "10200" },
          ],
        },
        {
          id: 2,
          name: "Gampaha",
          name_si: "ගම්පහ",
          name_ta: "கம்பகா",
          cities: [
            { id: 8, name: "Gampaha", postcode: "11000" },
            { id: 9, name: "Negombo", postcode: "11500" },
            { id: 10, name: "Ja-Ela", postcode: "11350" },
            { id: 11, name: "Wattala", postcode: "11300" },
            { id: 12, name: "Kandana", postcode: "11320" },
            { id: 13, name: "Minuwangoda", postcode: "11550" },
            { id: 14, name: "Katunayake", postcode: "11450" },
          ],
        },
        {
          id: 3,
          name: "Kalutara",
          name_si: "කළුතර",
          name_ta: "களுத்துறை",
          cities: [
            { id: 15, name: "Kalutara", postcode: "12000" },
            { id: 16, name: "Beruwala", postcode: "12070" },
            { id: 17, name: "Panadura", postcode: "12500" },
            { id: 18, name: "Horana", postcode: "12400" },
            { id: 19, name: "Bandaragama", postcode: "12530" },
            { id: 20, name: "Matugama", postcode: "12100" },
          ],
        },
      ],
    },
    {
      id: 2,
      name: "Central Province",
      name_si: "මධ්යම පළාත",
      name_ta: "මத்திய மாகාணம்",
      districts: [
        {
          id: 4,
          name: "Kandy",
          name_si: "මහනුවර",
          name_ta: "கண்டி",
          cities: [
            { id: 21, name: "Kandy", postcode: "20000" },
            { id: 22, name: "Peradeniya", postcode: "20400" },
            { id: 23, name: "Gampola", postcode: "20500" },
            { id: 24, name: "Nawalapitiya", postcode: "20650" },
            { id: 25, name: "Wattegama", postcode: "20800" },
          ],
        },
        {
          id: 5,
          name: "Matale",
          name_si: "මාතලේ",
          name_ta: "மாத்தளை",
          cities: [
            { id: 26, name: "Matale", postcode: "21000" },
            { id: 27, name: "Dambulla", postcode: "21100" },
            { id: 28, name: "Rattota", postcode: "21400" },
            { id: 29, name: "Sigiriya", postcode: "21120" },
          ],
        },
        {
          id: 6,
          name: "Nuwara Eliya",
          name_si: "නුවරඑළිය",
          name_ta: "நுவரெலியா",
          cities: [
            { id: 30, name: "Nuwara Eliya", postcode: "22200" },
            { id: 31, name: "Hatton", postcode: "22000" },
            { id: 32, name: "Talawakele", postcode: "22100" },
            { id: 33, name: "Nanu Oya", postcode: "22150" },
          ],
        },
      ],
    },
    {
      id: 3,
      name: "Southern Province",
      name_si: "දකුණු පළාත",
      name_ta: "தெන් மாகාணம்",
      districts: [
        {
          id: 7,
          name: "Galle",
          name_si: "ගාල්ල",
          name_ta: "காலி",
          cities: [
            { id: 34, name: "Galle", postcode: "80000" },
            { id: 35, name: "Ambalangoda", postcode: "80300" },
            { id: 36, name: "Hikkaduwa", postcode: "80240" },
            { id: 37, name: "Elpitiya", postcode: "80400" },
            { id: 38, name: "Bentota", postcode: "80500" },
          ],
        },
        {
          id: 8,
          name: "Matara",
          name_si: "මාතර",
          name_ta: "மாத்தறை",
          cities: [
            { id: 39, name: "Matara", postcode: "81000" },
            { id: 40, name: "Weligama", postcode: "81700" },
            { id: 41, name: "Dickwella", postcode: "81200" },
            { id: 42, name: "Deniyaya", postcode: "81500" },
            { id: 43, name: "Hakmana", postcode: "81300" },
          ],
        },
        {
          id: 9,
          name: "Hambantota",
          name_si: "හම්බන්තොට",
          name_ta: "அம்பාந்தோட்டை",
          cities: [
            { id: 44, name: "Hambantota", postcode: "82000" },
            { id: 45, name: "Tangalle", postcode: "82200" },
            { id: 46, name: "Beliatta", postcode: "82400" },
            { id: 47, name: "Tissamaharama", postcode: "82600" },
            { id: 48, name: "Ambalantota", postcode: "82100" },
          ],
        },
      ],
    },
    {
      id: 4,
      name: "Northern Province",
      name_si: "උතුරු පළාත",
      name_ta: "வட மாகාணம்",
      districts: [
        {
          id: 10,
          name: "Jaffna",
          name_si: "යාපනය",
          name_ta: "யாழ்ப்பாணம்",
          cities: [
            { id: 49, name: "Jaffna", postcode: "40000" },
            { id: 50, name: "Chavakachcheri", postcode: "40100" },
            { id: 51, name: "Point Pedro", postcode: "40300" },
            { id: 52, name: "Nallur", postcode: "40000" },
          ],
        },
        {
          id: 11,
          name: "Kilinochchi",
          name_si: "කිලිනොච්චිය",
          name_ta: "கிளிநொச்சி",
          cities: [
            { id: 53, name: "Kilinochchi", postcode: "44000" },
            { id: 54, name: "Paranthan", postcode: "44000" },
          ],
        },
        {
          id: 12,
          name: "Mannar",
          name_si: "මන්නාරම",
          name_ta: "மன்னார்",
          cities: [
            { id: 55, name: "Mannar", postcode: "41000" },
            { id: 56, name: "Madhu", postcode: "41000" },
          ],
        },
        {
          id: 13,
          name: "Mullaitivu",
          name_si: "මුලතිව්",
          name_ta: "முல்லைத்தீவு",
          cities: [
            { id: 57, name: "Mullaitivu", postcode: "42000" },
            { id: 58, name: "Puthukkudiyiruppu", postcode: "42000" },
          ],
        },
        {
          id: 14,
          name: "Vavuniya",
          name_si: "වවුනියාව",
          name_ta: "வவுனியா",
          cities: [
            { id: 59, name: "Vavuniya", postcode: "43000" },
            { id: 60, name: "Vavuniya South", postcode: "43000" },
          ],
        },
      ],
    },
    {
      id: 5,
      name: "Eastern Province",
      name_si: "නැගෙනහිර පළාත",
      name_ta: "கிழக்கு மாகාணம்",
      districts: [
        {
          id: 15,
          name: "Batticaloa",
          name_si: "මඩකලපුව",
          name_ta: "மட்டக்களப்பு",
          cities: [
            { id: 61, name: "Batticaloa", postcode: "30000" },
            { id: 62, name: "Kattankudy", postcode: "30100" },
            { id: 63, name: "Eravur", postcode: "30300" },
            { id: 64, name: "Valaichchenai", postcode: "30400" },
          ],
        },
        {
          id: 16,
          name: "Ampara",
          name_si: "අම්පාර",
          name_ta: "அம்பாறை",
          cities: [
            { id: 65, name: "Ampara", postcode: "32000" },
            { id: 66, name: "Kalmunai", postcode: "32300" },
            { id: 67, name: "Akkaraipattu", postcode: "32400" },
            { id: 68, name: "Sainthamaruthu", postcode: "32200" },
            { id: 69, name: "Pottuvil", postcode: "32500" },
          ],
        },
        {
          id: 17,
          name: "Trincomalee",
          name_si: "ත්රිකුණාමලය",
          name_ta: "திருகோணமலை",
          cities: [
            { id: 70, name: "Trincomalee", postcode: "31000" },
            { id: 71, name: "Kinniya", postcode: "31100" },
            { id: 72, name: "Muttur", postcode: "31200" },
            { id: 73, name: "Kantalai", postcode: "31300" },
          ],
        },
      ],
    },
    {
      id: 6,
      name: "North Western Province",
      name_si: "වයඹ පළාත",
      name_ta: "வட மேல் மாகாணம்",
      districts: [
        {
          id: 18,
          name: "Kurunegala",
          name_si: "කුරුණෑගල",
          name_ta: "குருநாகல்",
          cities: [
            { id: 74, name: "Kurunegala", postcode: "60000" },
            { id: 75, name: "Kuliyapitiya", postcode: "60200" },
            { id: 76, name: "Nikaveratiya", postcode: "60400" },
            { id: 77, name: "Pannala", postcode: "60100" },
          ],
        },
        {
          id: 19,
          name: "Puttalam",
          name_si: "පුත්තලම",
          name_ta: "புத்தளம்",
          cities: [
            { id: 78, name: "Puttalam", postcode: "61300" },
            { id: 79, name: "Chilaw", postcode: "61000" },
            { id: 80, name: "Wennappuwa", postcode: "61170" },
            { id: 81, name: "Maho", postcode: "60600" },
          ],
        },
      ],
    },
    {
      id: 7,
      name: "North Central Province",
      name_si: "උතුරු මැද පළාත",
      name_ta: "வட மத்திய மாகாணம்",
      districts: [
        {
          id: 20,
          name: "Anuradhapura",
          name_si: "අනුරාධපුර",
          name_ta: "அனுராதபுரம்",
          cities: [
            { id: 82, name: "Anuradhapura", postcode: "50000" },
            { id: 83, name: "Mihintale", postcode: "50300" },
            { id: 84, name: "Kekirawa", postcode: "50100" },
            { id: 85, name: "Eppawala", postcode: "50200" },
          ],
        },
        {
          id: 21,
          name: "Polonnaruwa",
          name_si: "පොළොන්නරුව",
          name_ta: "பொலன்னறுவை",
          cities: [
            { id: 86, name: "Polonnaruwa", postcode: "51000" },
            { id: 87, name: "Kaduruwela", postcode: "51000" },
            { id: 88, name: "Medirigiriya", postcode: "51500" },
          ],
        },
      ],
    },
    {
      id: 8,
      name: "Uva Province",
      name_si: "ඌව පළාත",
      name_ta: "ஊவா மாகாணம்",
      districts: [
        {
          id: 22,
          name: "Badulla",
          name_si: "බදුල්ල",
          name_ta: "பதுளை",
          cities: [
            { id: 89, name: "Badulla", postcode: "90000" },
            { id: 90, name: "Bandarawela", postcode: "90100" },
            { id: 91, name: "Haputale", postcode: "90160" },
            { id: 92, name: "Welimada", postcode: "90200" },
            { id: 93, name: "Passara", postcode: "90500" },
          ],
        },
        {
          id: 23,
          name: "Monaragala",
          name_si: "මොණරාගල",
          name_ta: "மொணராகலை",
          cities: [
            { id: 94, name: "Monaragala", postcode: "91000" },
            { id: 95, name: "Wellawaya", postcode: "91200" },
            { id: 96, name: "Bibile", postcode: "91500" },
            { id: 97, name: "Kataragama", postcode: "91400" },
          ],
        },
      ],
    },
    {
      id: 9,
      name: "Sabaragamuwa Province",
      name_si: "සබරගමුව පළාත",
      name_ta: "சபரகமுவ மாகாணம்",
      districts: [
        {
          id: 24,
          name: "Ratnapura",
          name_si: "රත්නපුර",
          name_ta: "இரத்தினபுரி",
          cities: [
            { id: 98, name: "Ratnapura", postcode: "70000" },
            { id: 99, name: "Embilipitiya", postcode: "70200" },
            { id: 100, name: "Balangoda", postcode: "70100" },
            { id: 101, name: "Pelmadulla", postcode: "70000" },
          ],
        },
        {
          id: 25,
          name: "Kegalle",
          name_si: "කෑගල්ල",
          name_ta: "கேகாலை",
          cities: [
            { id: 102, name: "Kegalle", postcode: "71000" },
            { id: 103, name: "Mawanella", postcode: "71500" },
            { id: 104, name: "Warakapola", postcode: "71600" },
            { id: 105, name: "Aranayake", postcode: "71100" },
          ],
        },
      ],
    },
  ],
};
